env:
  global:
    - NDK_VERSION=r10e
sudo: false
language:
  - android
before_install:
- openssl aes-256-cbc -K $encrypted_4a609b7f3125_key -iv $encrypted_4a609b7f3125_iv
  -in my-release-key.keystore.enc -out my-release-key.keystore -d
install:
  - cd ..
  - git clone --depth=50 --branch=ci2 https://github.com/galeksandrp/orbot.git
  - cd orbot
  - git rm -rf $(git submodule | grep -v libevent | grep -v openssl | cut -d ' ' -f 2)
  - git submodule update --init --recursive
  - mv $TRAVIS_BUILD_DIR external/tor
  - cd external
  - wget https://github.com/galeksandrp/orbot/releases/download/deploy-15.2.0-RC-8-multi-9-gc943043/app-release.apk
  - wget https://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.bin
  - chmod +x android-ndk-$NDK_VERSION-linux-x86_64.bin
  - ./android-ndk-$NDK_VERSION-linux-x86_64.bin | egrep -v ^Extracting
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
  - export PATH=${PATH}:${ANDROID_NDK_HOME}
before_script:
- |
  echo 'assets-tor: tor' >> Makefile
- echo '	install -d ../orbotservice/src/main/assets/$(APP_ABI)' >> Makefile
- echo '	-$(STRIP) bin/tor' >> Makefile
- echo '	-zip ../orbotservice/src/main/assets/$(APP_ABI)/tor.mp3 bin/tor' >> Makefile
- echo '	-zip app-release.apk ../orbotservice/src/main/assets/$(APP_ABI)/tor.mp3' >> Makefile
script:
- make assets-tor
before_deploy:
  - cp app-release.apk app-release-signed.apk
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore tor/my-release-key.keystore -storepass $KEYSTORE_PASS app-release-signed.apk alias_name
  - $ANDROID_HOME/build-tools/24.0.0/zipalign -v 4 app-release-signed.apk app-release-signed-aligned.apk
  - cd $TRAVIS_BUILD_DIR
  - echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
  - git tag deploy-$(git describe --always) $TRAVIS_COMMIT || true
  - git push origin deploy-$(git describe --always)
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: "*.apk"
  file_glob: true
  overwrite: true
  on:
    all_branches: true
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
